### PR TITLE
Support brightness in all lightbulbs

### LINKED ISSUE #10: Add support for brightness adjustments
It seems that the adapter does not allow for controlling the brightness of the lightbulbs.

It would be great to see that feature added :)

### PR DESCRIPTION
**Pull request by zbraniecki**
Fixes #10

### CODE REVIEW

**Comment by steveatinfincia** [comment]
Sorry for the delay, and thanks for the PR :)

The lifx-adapter code does have [brightness support](https://github.com/infincia/lifx-adapter/blob/master/pkg/lifx_device.py#L161) for the color bulbs, it just doesn't show a separate level controller for those bulbs.

As I recall, the reason we only had the level control enabled for non-color bulbs was due to the way the gateway interface handled color selection, which technically allowed setting a brightness level indirectly as a result of changing the color controls.

I *think* someone was working on a newer interface for bulbs that made more sense than just making it part of the color selection, but I haven't checked in a while. I need to reinstall my gateway and have a look.

I know the LIFX apps for iPhone/Android do show a separate level control, and it's convenient for sure so I'm fine with changing it if there's not a better interface yet.

**Comment by zbraniecki** [comment]
ping? @steveatinfincia any update?

**Comment by mrstegeman** [comment]
@zbraniecki I'm maintaining this add-on now.

We (the Mozilla IoT team) made a decision a long time ago to omit color temperature and brightness controls for RGB bulbs. The brightness is actually a component of the color, so it can be controlled by the color picker. The color temperature can be emulated by the RGB bulb. I know that typically, there are separate light arrays for white and RGB, but we decided that was just a technical detail.

Personally, as a "power user", I would like to have separate controls for everything, but for a non-technical person, this UI probably makes more sense. Feel free to argue otherwise!

**Comment by zbraniecki** [comment]
I'm not sure if I understand.

I use lifx with their app, which allows me to control brightness and color separately. I also use Google Home integration which allows me to control brightness and color separately.

Are you saying that those two are for power users and their UX is too complicated?

I'd even say that Lifx app has one more feature - they actually provide three separate dials:
 - color palette
 - brightness
 - warmth

Which is super useful. Color, while funny, is really a gimmick. I don't know anyone who'd walk around their house and change their lights from red to blue to green too often. But brightness is something I need to adjust daily, often in a cycle.
Warmth is useful to control when I want to move between "keep me up" (colder) and "I'm dialing down"  (warmer) mode in my bedroom.

In Lifx app I also can tie it to the circadian rhythm and adjust brightness and warmth to when the sun rises and sets.

I see brightness as the most important feature of a lightbulb. Having to carefully move the pointer via the color picker to adjust brightness seems like a very error-prone UX.

**Comment by mrstegeman** [comment]
As I said, I'd personally prefer to have brightness and color temperature controls as well.

The issue is that visually in our UI, when you change the brightness, you're also changing the color, which could confuse users. Conversely, when you change the color temperature, the actual color property will NOT change, because that's typically controlled by a separate light array in the bulb. So you then have the following 3 situations:
1. Change RGB color
    * Color property changes
    * Brightness property changes
    * Color temperature property does not change
2. Change brightness
    * Color property **might** change, depending on which mode the bulb is in
    * Brightness property changes
    * Color temperature property does not change
3. Change color temperature
    * Color property does not change, or may switch to black or white (depending on the bulb's software)
    * Brightness property does not change
    * Color temperature property changes

The point is that the UI changes are not really consistent from a user perspective when changing any of those 3 properties.

@dhylands @hobinjk @benfrancis Do you have any new thoughts on this? It's been a while since we really discussed. A similar discussion just happened here: https://github.com/mozilla-iot/zigbee-adapter/issues/147#issuecomment-508728870

**Comment by hobinjk** [comment]
My thoughts are still that we need a custom color picker control that does rgb/brightness/color temperature in one place and until that is implemented the current solution is the least bad

**Comment by benfrancis** [comment]
> My thoughts are still that we need a custom color picker control that does rgb/brightness/color temperature in one place and until that is implemented the current solution is the least bad

I tend to agree with this. We could create a poly-fill for color inputs to use our own colour picker which does these things well. The default one on Firefox for Android is extremely limited (and I don't think all browsers even have one yet).

**Comment by mrstegeman** [comment]
Ok, let's just defer to mozilla-iot/gateway#1378

**Comment by stripTM** [comment]
As I commented in github in Yeelight bulbs the color #FFFFFF is not 100% bright

Once you change the color it is impossible to return to full brightness.

If you keep only the color, what you should do is infer the brightness and set it.

E.g. the user selects #FFFFFF, the bulb is sent the commands yeelight.color("#FFFFFF"); yeelight->bright(100):

**Comment by mrstegeman** [comment]
The brightness is already a component of the color, so there's no need to infer the brightness.

The problem is that most RGB bulbs have two different LED arrays, a color array and a white array. When you're in RGB mode, white (`#FFFFFF`) will not look the same as it will in white mode.

**Comment by agentff6600** [comment]
I completely understand that it would be neat to have all properties (colour, brightness and colour temperature) in one control. I have concerns that users of existing light systems trained themselves to use the conventions of the system they initially bought, in my case LIFX.

The user perspective of those 3 properties is, therefore, different depending on which system they have.

Just out of curiosity (without knowing if it relates. also please excuse if I bring up old stuff that has been discussed elsewhere): How can I change only the brightness with a dimmer with only the colour selector that is available now? In my problem, for example, I can't change the brightness of a LIFX 1000 lamp. Only colour.

**Comment by mrstegeman** [comment]
It entirely depends on your browser + platform choice. For instance, with Firefox on macOS, the color picker has a brightness slider.

**Pull request closed without merging**
